version: "3.9"

services:
  app:
    image: ghcr.io/sec-group-a/pern_inventory_manager:latest
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASS}@db:5432/${DB_NAME}
    volumes:
      - app_data:/app/uploads # Persistent volume for uploaded files
    ports:
      - "8080:8080" # Adjust based on your app’s exposed port

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pg_data:/var/lib/postgresql/data # Persistent volume for DB storage
    ports:
      - "5432:5432"

volumes:
  pg_data: # Persistent storage for PostgreSQL
  app_data: # Persistent storage for app uploads
